name: Deploy to Reg.ru

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REGRU_HOST }}
          username: ${{ secrets.REGRU_USER }}
          key: ${{ secrets.REGRU_KEY }}
          script: |
            cd /www/site100.ru/projects/deploy/
            git pull
